flyway.url=jdbc:postgresql://localhost:5432/cinema-postgres
flyway.user=postgres
flyway.password=postgres123
flyway.schemas=auth,catalog,cinema,scheduling,booking
flyway.createSchemas=true
flyway.baselineOnMigrate=true
