spring:
  application:
    name: cinema-iam
  jackson:
    time-zone: ${APP_TIMEZONE}
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: ${APP_TIMEZONE}
        default_schema: auth
    hibernate:
      ddl-auto: none
    show-sql: false
  flyway:
    enabled: true
    schemas: auth
    create-schemas: true
    baseline-on-migrate: true
    repair-on-migrate: true
    out-of-order: true
  config:
    import: "optional:file:../../.env[.properties]"
  profiles:
    active: dev
logging:
  level:
    org.flywaydb: DEBUG
    springframework.boot.autoconfigure.flyway: DEBUG


management:
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318/v1/traces}
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never
