spring:
  application:
    name: cinema-notification
  jackson:
    time-zone: ${APP_TIMEZONE}
  config:
    import: "optional:file:../../.env[.properties]"
  profiles:
    active: dev

management:
  tracing:
    sampling:
      probability: 1.0
  otlp:
    tracing:
      endpoint: ${OTEL_EXPORTER_OTLP_ENDPOINT:http://localhost:4318/v1/traces}
