FROM eclipse-temurin:17-jre-alpine

WORKDIR /app

ARG MODULE_NAME

COPY ${MODULE_NAME}/target/*.jar app.jar

ENV JAVA_OPTS="-Xms256m -Xmx512m"

ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar app.jar"]
